import React, { useState, useEffect } from 'react';
import { X, Copy, Check, Loader2, Sparkles } from 'lucide-react';
import { GraphNode } from '../types';
import { generatePrompts, MuseStar, MuseStarPrompt } from '../services/museStarService';

const TOKEN_KEY = 'graph_starz_jwt_token';

interface MuseStarPanelProps {
  museStar: GraphNode | null;
  onClose: () => void;
}

const MuseStarPanel: React.FC<MuseStarPanelProps> = ({ museStar, onClose }) => {
  const [prompts, setPrompts] = useState<MuseStarPrompt[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);

  useEffect(() => {
    if (!museStar) {
      setPrompts([]);
      setError(null);
      return;
    }

    const fetchPrompts = async () => {
      const token = localStorage.getItem(TOKEN_KEY);
      if (!token) {
        setError('Authentication required');
        return;
      }

      setIsLoading(true);
      setError(null);

      try {
        // Convert GraphNode to MuseStar format
        const museStarData: MuseStar = {
          id: museStar.id,
          type: 'muse_star',
          userId: '', // Not needed for prompt generation
          targetAttributes: museStar.targetAttributes || [],
          context: {
            nearbyImages: museStar.nearbyImages || [],
            attributeGap: museStar.attributeGap || '',
            imageCount: museStar.imageCount || 0,
          },
        };

        const response = await generatePrompts(museStarData, token);
        setPrompts(response.prompts);
      } catch (err: any) {
        setError(err.message || 'Failed to generate prompts');
      } finally {
        setIsLoading(false);
      }
    };

    fetchPrompts();
  }, [museStar]);

  const handleCopy = async (text: string, index: number) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedIndex(index);
      setTimeout(() => setCopiedIndex(null), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  if (!museStar) return null;

  return (
    <div className="fixed inset-y-0 right-0 w-full max-w-md bg-surface border-l border-gray-700 shadow-2xl z-50 flex flex-col">
      {/* Header */}
      <div className="p-6 border-b border-gray-700 flex justify-between items-start">
        <div>
          <h2 className="text-xl font-bold text-white flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-amber-400" />
            Ideas for this part of your map
          </h2>
          <p className="text-sm text-gray-400 mt-1">
            Generated by the AI Muse based on your images and the global graph index
          </p>
        </div>
        <button
          onClick={onClose}
          className="text-gray-400 hover:text-white transition-colors"
        >
          <X className="w-6 h-6" />
        </button>
      </div>

      {/* Body */}
      <div className="flex-1 overflow-y-auto p-6">
        {/* Muse Star Info */}
        <div className="bg-gray-800/50 rounded-lg p-4 border border-amber-500/30 mb-6">
          <p className="text-sm text-amber-300 font-semibold mb-2">
            Suggested attributes:
          </p>
          <div className="flex flex-wrap gap-2 mb-3">
            {museStar.targetAttributes?.map((attr, i) => (
              <span
                key={i}
                className="px-3 py-1 rounded-full bg-amber-900/30 text-amber-200 text-xs border border-amber-500/30"
              >
                {attr.type}: {attr.value}
              </span>
            ))}
          </div>
          {museStar.attributeGap && (
            <p className="text-xs text-gray-400 italic">{museStar.attributeGap}</p>
          )}
        </div>

        {/* Loading State */}
        {isLoading && (
          <div className="flex flex-col items-center justify-center py-12">
            <Loader2 className="w-8 h-8 text-primary animate-spin mb-3" />
            <p className="text-sm text-gray-400">AI Muse is crafting prompts...</p>
          </div>
        )}

        {/* Error State */}
        {error && (
          <div className="bg-red-900/20 border border-red-500/30 rounded-lg p-4">
            <p className="text-sm text-red-300">{error}</p>
          </div>
        )}

        {/* Prompts */}
        {!isLoading && !error && prompts.length > 0 && (
          <div className="space-y-4">
            {prompts.map((prompt, index) => (
              <div
                key={index}
                className="bg-gray-800/50 border border-gray-700 rounded-lg p-4 hover:border-primary/50 transition-colors"
              >
                <div className="flex items-start justify-between mb-2">
                  <span
                    className={`px-2 py-1 rounded text-xs font-semibold ${
                      prompt.label === 'Safe'
                        ? 'bg-green-900/30 text-green-300 border border-green-500/30'
                        : prompt.label === 'Bold'
                        ? 'bg-blue-900/30 text-blue-300 border border-blue-500/30'
                        : 'bg-purple-900/30 text-purple-300 border border-purple-500/30'
                    }`}
                  >
                    {prompt.label}
                  </span>
                  <button
                    onClick={() => handleCopy(prompt.text, index)}
                    className="p-2 rounded hover:bg-gray-700 transition-colors text-gray-400 hover:text-white"
                    title="Copy to clipboard"
                  >
                    {copiedIndex === index ? (
                      <Check className="w-4 h-4 text-green-400" />
                    ) : (
                      <Copy className="w-4 h-4" />
                    )}
                  </button>
                </div>
                <p className="text-sm text-gray-200 leading-relaxed">{prompt.text}</p>
              </div>
            ))}
          </div>
        )}

        {/* Empty State */}
        {!isLoading && !error && prompts.length === 0 && (
          <div className="text-center py-12">
            <p className="text-gray-400">No prompts available for this Muse Star.</p>
          </div>
        )}
      </div>

      {/* Footer */}
      <div className="p-6 border-t border-gray-700 bg-gray-900/30">
        <p className="text-xs text-gray-500 text-center">
          Use these prompts with your favorite AI image generator to expand your map
        </p>
      </div>
    </div>
  );
};

export default MuseStarPanel;
